#!/usr/bin/env bash
# PreToolUse hook (Claude Code and Codex): refuse edits to generated or
# vendored files. Exit 2 blocks the tool call and shows stderr to the agent,
# which then edits the source and regenerates instead.
set -u
. "$(dirname "$0")/lib.sh"
status=0
while IFS= read -r path; do
  case "$path" in
    *_templ.go)
      echo "Blocked: $path is generated by templ. Edit the matching .templ file, then run \`task generate\`." >&2
      status=2 ;;
    */internal/web/static/vendor/*)
      echo "Blocked: $path is a vendored third-party file. Replace it with a new upstream release (see internal/web/static/vendor/README.md), never edit it." >&2
      status=2 ;;
    */.codex/agents/*|*/.agents/skills/*)
      echo "Blocked: $path is generated from .claude/agents or .claude/skills. Edit the source there; the Codex copy regenerates (\`task ai:sync\`)." >&2
      status=2 ;;
  esac
done < <(edited_paths)
exit $status
