// Package testutil holds helpers shared by tests: finding ffmpeg, the
// repository root, and the synthetic media fixtures generated by
// scripts/make-fixtures.sh. It is imported only from _test.go files.
package testutil

import (
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"testing"
)

// RequireEnv makes a missing ffmpeg or fixture a failure instead of a skip.
// CI sets it, so a skip there cannot hide a broken test.
const RequireEnv = "JELLYTRIM_REQUIRE_FFMPEG"

// fixtures maps fixture names (as used for the ffprobe JSON in
// internal/media/testdata/probe) to clips under dev/media. Keep in step
// with scripts/make-fixtures.sh.
var fixtures = map[string]string{
	"h264-1080p":        "movies/Alpha (2019)/Alpha (2019).mkv",
	"hevc-1080p":        "movies/Bravo (2020)/Bravo (2020).mkv",
	"h264-2160p":        "movies/Charlie (2021)/Charlie (2021).mkv",
	"hevc-2160p-hdr10":  "movies/Delta (2022)/Delta (2022).mkv",
	"hevc-1080p-hlg":    "movies/Echo (2022)/Echo (2022).mkv",
	"av1-1080p":         "movies/Foxtrot (2023)/Foxtrot (2023).mkv",
	"multi-audio-subs":  "movies/Golf (2018)/Golf (2018).mkv",
	"anime-ass":         "movies/Hotel (2017)/Hotel (2017).mkv",
	"scope-1080p":       "movies/India (2016)/India (2016).mkv",
	"interlaced":        "movies/Juliet (2005)/Juliet (2005).mkv",
	"mp4-movtext-cover": "movies/Kilo (2015)/Kilo (2015).mp4",
	"hard-linked":       "movies/Lima (2014)/Lima (2014).mkv",
	"tv-episode":        "tv/Mike Show/Season 01/Mike Show - S01E01.mkv",
	"tv-hevc-720p":      "tv/November Show/Season 01/November Show - S01E01.mkv",
}

// FixtureNames lists the known fixture names, sorted.
func FixtureNames() []string {
	names := make([]string, 0, len(fixtures))
	for n := range fixtures {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// missing skips the test, or fails it when RequireEnv is "1".
func missing(t testing.TB, msg string) {
	t.Helper()
	if os.Getenv(RequireEnv) == "1" {
		t.Fatal(msg)
	}
	t.Skip(msg)
}

// RequireFFmpeg returns the ffmpeg and ffprobe to test with: the
// JELLYTRIM_FFMPEG and JELLYTRIM_FFPROBE variables when set, otherwise the
// binaries on PATH. It skips the test when either is missing.
func RequireFFmpeg(t testing.TB) (ffmpegPath, ffprobePath string) {
	t.Helper()
	ffmpegPath = findTool(os.Getenv("JELLYTRIM_FFMPEG"), "ffmpeg")
	ffprobePath = findTool(os.Getenv("JELLYTRIM_FFPROBE"), "ffprobe")
	if ffmpegPath == "" || ffprobePath == "" {
		missing(t, "ffmpeg and ffprobe are needed for this test (install them or set JELLYTRIM_FFMPEG and JELLYTRIM_FFPROBE)")
	}
	return ffmpegPath, ffprobePath
}

// findTool resolves an explicit path, or looks name up on PATH. It avoids
// os/exec, which only internal/ffmpeg may import.
func findTool(explicit, name string) string {
	if explicit != "" {
		if isExecutable(explicit) {
			return explicit
		}
		return ""
	}
	if runtime.GOOS == "windows" {
		name += ".exe"
	}
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" {
			continue
		}
		if p := filepath.Join(dir, name); isExecutable(p) {
			return p
		}
	}
	return ""
}

func isExecutable(path string) bool {
	fi, err := os.Stat(path) //nolint:gosec // a tool path from the test environment, only checked for existence
	if err != nil || fi.IsDir() {
		return false
	}
	return runtime.GOOS == "windows" || fi.Mode().Perm()&0o111 != 0
}

// RepoRoot returns the repository root (the directory holding go.mod).
func RepoRoot(t testing.TB) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("testutil: cannot locate the source file")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("testutil: no go.mod at %s: %v", root, err)
	}
	return root
}

// Fixture returns the path of a generated media clip by fixture name (for
// example "h264-1080p"). It skips the test when the clip has not been
// generated. Tests must not change the returned file; use CopyFixture.
func Fixture(t testing.TB, name string) string {
	t.Helper()
	rel, ok := fixtures[name]
	if !ok {
		t.Fatalf("testutil: unknown fixture %q (known: %v)", name, FixtureNames())
	}
	path := filepath.Join(RepoRoot(t), "dev", "media", filepath.FromSlash(rel))
	if _, err := os.Stat(path); err != nil {
		missing(t, "fixture "+name+" is missing: run task dev:fixtures")
	}
	return path
}

// CopyFixture copies a fixture clip into a fresh t.TempDir() and returns the
// copy's path. The copy keeps the clip's file name.
func CopyFixture(t testing.TB, name string) string {
	t.Helper()
	src := Fixture(t, name)
	dst := filepath.Join(t.TempDir(), filepath.Base(src))
	if err := copyFile(src, dst); err != nil {
		t.Fatalf("testutil: copying fixture %s: %v", name, err)
	}
	return dst
}

func copyFile(src, dst string) (err error) {
	in, err := os.Open(src) //nolint:gosec // src is a fixture path from the table above
	if err != nil {
		return err
	}
	defer func() { _ = in.Close() }()
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600) //nolint:gosec // dst is inside t.TempDir()
	if err != nil {
		return err
	}
	defer func() {
		if cerr := out.Close(); err == nil {
			err = cerr
		}
	}()
	_, err = io.Copy(out, in)
	return err
}

// ProbeJSON returns the committed ffprobe output for a fixture from
// internal/media/testdata/probe: the stream probe and the first-frame probe
// (nil when there is none).
func ProbeJSON(t testing.TB, name string) (probe, frames []byte) {
	t.Helper()
	root, err := os.OpenRoot(filepath.Join(RepoRoot(t), "internal", "media", "testdata", "probe"))
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = root.Close() }()
	probe, err = root.ReadFile(name + ".json")
	if err != nil {
		t.Fatalf("testutil: probe JSON for %s: %v", name, err)
	}
	frames, err = root.ReadFile(name + ".frames.json")
	if err != nil && !os.IsNotExist(err) {
		t.Fatalf("testutil: frame JSON for %s: %v", name, err)
	}
	return probe, frames
}
